name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
      full-test:
        runs-on: self-hosted
        timeout-minutes: 720
        steps:
          - uses: actions/checkout@v3
            with:
              clean: false
              submodules: 'recursive'
          - uses: webfactory/ssh-agent@v0.5.4
            with:
                 ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: init conf
            run: |
              mkdir -p build/conf
              echo 'DL_DIR = "/tmp/yocto_cache/downloads"' > build/conf/site.conf 
              echo 'SSTATE_DIR = "/tmp/yocto_cache/sstate-cache"' >> build/conf/site.conf 
              echo 'INHERIT += "rm_work"' >> build/conf/site.conf
          - name: Run build
            timeout-minutes: 600
            run: |
               docker run --rm \
                 -v "$HOME/Assignments/yocto_cache/downloads/:/tmp/yocto_cache/downloads" \
                 -v "$HOME/Assignments/yocto_cache/sstate-cache/:/tmp/yocto_cache/sstate-cache" \
                 -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent \
                 -e GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" \
                 -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                 cuaesd/aesd-autotest:24-assignment6-yocto \
                 --workdir=${GITHUB_WORKSPACE} \
                 ./build.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
          - name: Run full test
            timeout-minutes: 15
            run: |
               docker run --rm \
                 -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                 cuaesd/aesd-autotest:assignment6-yocto \
                 --workdir=${GITHUB_WORKSPACE} \
                 ./full-test.sh
